#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR 0x08
#define KERNEL_DATA_SELECTOR 0x10


#define TOTAL_INTERRUPTS 512



#define SECTOR_SIZE 512

#define MAX_FILESYSTEMS 12
#define MAX_FILE_DESCRIPTORS 512

#define MAX_PATH_SIZE 108


#define TOTAL_GDT_SEGMENTS 6


#define MAX_PROGRAM_ALLOCATIONS 1024
#define MAX_PROCESSES 12


#define USER_DATA_SEGMENT 0x23
#define USER_CODE_SEGMENT 0x1b

#define MAX_ISR80H_COMMANDS 1024

#define KEYBOARD_BUFFER_SIZE 1024

#endif